#!/bin/sh
_CONDA_ROOT="C:/Users/Trish/Documents/stat 207"
# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause
\. "$_CONDA_ROOT/etc/profile.d/conda.sh" || return $?
conda activate "$@"
