_wandb:
    value:
        cli_version: 0.25.0
        e:
            ulxnbz2xmpim5crz9ic8dttunv7whdfa:
                cpu_count: 12
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1022632464384"
                        used: "518532714496"
                email: tnair@andrew.cmu.edu
                executable: C:\Users\Trish\new_ana\python.exe
                git:
                    commit: 12b082a9ac9b423fea21507f5836b074f3224910
                    remote: https://github.com/tna-git/school_projects
                host: Kuttamboos
                memory:
                    total: "16780767232"
                os: Windows-11-10.0.26200-SP0
                program: <python with no main file>
                python: CPython 3.12.7
                root: C:\Users\Trish\Documents\CMU\Capstone
                startedAt: "2026-02-20T23:59:29.579765Z"
                writerId: ulxnbz2xmpim5crz9ic8dttunv7whdfa
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 35
                - 41
            "2":
                - 1
                - 35
                - 41
            "3":
                - 1
                - 2
                - 13
                - 16
            "4": 3.12.7
            "5": 0.25.0
            "8":
                - 1
                - 3
            "10":
                - 20
            "12": 0.25.0
            "13": windows-amd64
batch_size:
    value: 32
dropout_rate:
    value: 0.005026545030577666
epochs:
    value: 3
hidden_size:
    value: 1024
lr:
    value: 0.00205651293994405
optimizer:
    value: adam
